server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.119.123:3306/mybatis?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: mybatis
    password: Mybatis@1234
  flyway:
    locations:
      - classpath:migration
logging:
  level:
    root: INFO
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.chenlei.domain