server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://192.168.119.123:3306/flyway?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: flyway
    password: Flyway@1234
    driver-class-name: com.mysql.jdbc.Driver
  flyway:
    locations: classpath:com/chenlei/flyway/db/mysql
